/**
 * postMessage protocol between AppHost (React) and CanvasFrame (iframe runtime).
 * All messages are strongly typed. sender must set { targetOrigin: '*' } when
 * using srcdoc iframes (origin is 'null').
 */

// ─── Host → Runtime ─────────────────────────────────────────────────────────

export type HostMessage =
  | InitMessage
  | PatchMessage
  | RequestHtmlMessage
  | DisableScriptsMessage;

export interface InitMessage {
  type: 'init';
  /** Serialized <section class="slide"> outer HTML for the current page */
  sectionHtml: string;
  /** file:// or blob: base URL so relative asset paths resolve */
  assetsBaseUrl: string;
}

export interface PatchMessage {
  type: 'patch';
  /** CSS path generated by runtime's buildStableSelector() */
  selector: string;
  ops: PatchOp[];
}

export type PatchOp =
  | { kind: 'text'; value: string }
  | { kind: 'attr'; name: string; value: string | null }
  | { kind: 'style'; name: string; value: string | null }
  | { kind: 'class'; add?: string[]; remove?: string[] };

export interface RequestHtmlMessage {
  type: 'request-html';
}

export interface DisableScriptsMessage {
  type: 'disable-scripts';
  /** true = move <script> to <template>, false = restore */
  disabled: boolean;
}

// ─── Runtime → Host ─────────────────────────────────────────────────────────

export type RuntimeMessage =
  | ReadyMessage
  | SelectMessage
  | ClearSelectMessage
  | PatchedMessage
  | ResponseHtmlMessage
  | RuntimeErrorMessage;

export interface ReadyMessage {
  type: 'ready';
}

export interface SelectMessage {
  type: 'select';
  selector: string;
  /** Element tag for attribute panel hints */
  tagName: string;
  bbox: SerializedDOMRect;
  /** Computed style snapshot for property panel pre-fill */
  styleSnapshot: StyleSnapshot;
  /** Selected element attributes relevant to the property panel (href, target, …) */
  attrs?: Record<string, string>;
  /** Current text content for back-filling the text editor in the panel */
  text?: string;
}

export interface ClearSelectMessage {
  type: 'clear-select';
}

export interface PatchedMessage {
  type: 'patched';
  /** Full outer HTML of the <section class="slide"> after patch */
  html: string;
}

export interface ResponseHtmlMessage {
  type: 'response-html';
  html: string;
}

export interface RuntimeErrorMessage {
  type: 'error';
  code: string;
  message: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

export interface SerializedDOMRect {
  x: number;
  y: number;
  width: number;
  height: number;
  top: number;
  left: number;
  bottom: number;
  right: number;
}

export interface StyleSnapshot {
  fontSize: string;
  fontWeight: string;
  color: string;
  textAlign: string;
  textDecoration: string;
}
